
ALTER TABLE `orders` ADD `instrument_id` VARCHAR(128) NULL DEFAULT NULL AFTER `id`;

CREATE TABLE IF NOT EXISTS versions (id INT AUTO_INCREMENT PRIMARY KEY, version INT NOT NULL)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4  COLLATE utf8mb4_general_ci;
