CREATE TABLE IF NOT EXISTS `telemetry_events` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `event_id` CHAR(36) NOT NULL,
  `event_type` VARCHAR(64) NOT NULL,
  `event_category` VARCHAR(32) NOT NULL,
  `occurred_at` DATETIME NOT NULL,
  `lab_id` VARCHAR(128) DEFAULT NULL,
  `instrument_id` VARCHAR(128) DEFAULT NULL,
  `machine_type` VARCHAR(128) DEFAULT NULL,
  `protocol` VARCHAR(32) DEFAULT NULL,
  `connection_mode` VARCHAR(32) DEFAULT NULL,
  `test_type` VARCHAR(128) DEFAULT NULL,
  `outcome` VARCHAR(32) NOT NULL DEFAULT 'success',
  `failure_code` VARCHAR(64) DEFAULT NULL,
  `event_count` INT UNSIGNED NOT NULL DEFAULT 1,
  `app_version` VARCHAR(32) DEFAULT NULL,
  `remote_uploaded_at` DATETIME DEFAULT NULL,
  `remote_batch_id` CHAR(36) DEFAULT NULL,
  `added_on` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_telemetry_events_event_id` (`event_id`),
  KEY `idx_telemetry_events_occurred_at` (`occurred_at`),
  KEY `idx_telemetry_events_type_time` (`event_type`, `occurred_at`),
  KEY `idx_telemetry_events_instrument_time` (`instrument_id`, `occurred_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
